"""rename phonepe_transaction_id to payment_transaction_id

Revision ID: cf2890cd76f7
Revises: 638c1f6e0c5a
Create Date: 2026-09-18 23:48:32.951252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2890cd76f7'
down_revision = '638c1f6e0c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_transaction_id', sa.String(length=120), nullable=True))
        batch_op.drop_column('phonepe_transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonepe_transaction_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('payment_transaction_id')

    # ### end Alembic commands ###
